//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.07 at 09:30:00 AM EDT 
//

package org.restsql.core.sqlresource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for HttpConfig complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RestConfig", propOrder = { "httpResponse", "csvConfig" })
public class RestConfig {

	@XmlElement(required = false)
	protected HttpResponse httpResponse;

	@XmlElement(required = false)
	protected CsvConfig csvConfig;

	public HttpResponse getHttpResponse() {
		return httpResponse;
	}

	public void setHttpResponse(HttpResponse httpResponse) {
		this.httpResponse = httpResponse;
	}

	public CsvConfig getCsvConfig() {
		return csvConfig;
	}

	public void setCsvConfig(CsvConfig csvConfig) {
		this.csvConfig = csvConfig;
	}

	@Override
	public String toString() {
		return "RestConfig [httpResponse=" + httpResponse + ", csvConfig="
				+ csvConfig + "]";
	}

}
